spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_improve2
    username: root
    password: root
    driver-class-name: com.jdbc.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl